version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  assignees:
  - shun-fix9
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: node-notifier
    versions:
    - 8.0.1
